name: hrd_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  shimmer: ^3.0.0
  pinput: ^6.0.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  camera: ^0.11.1
  google_maps_flutter: ^2.14.0
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
